Add streams bounds
meilisearch/MeiliES pull request #43
Opened 2019-05-18 14:56 UTC by qdequele

A stream name is composed as follow.

`{name}{:from}{:to}`

- name: the name of the stream, case sensitive, must not contain space (prefer dash-separated words).
- from: Specifies the first event number to begin with. Optional value, if it's not set meilies will start fron the end.
- to: Specify the last event number to send (exclusive range). Optional value, will never stop if it's not given.

**TODO:**
- [ ] Implementing the feature on each projects of the workspace
- [ ] No breaking
- [ ] Tests

2019-05-20 09:59 UTC, Kerollmops requested changes

2019-05-20 09:59 UTC, Kerollmops commented on README.md
> +- to: Specify the last event number to send (exclusive range). Optional value, will never stop if it's not given.
```suggestion
- to: Specifies the last event number to send (exclusive range). Optional, will never stop if it's not given.
```

2019-05-20 09:59 UTC, Kerollmops commented on README.md
> +- from: Specifies the first event number to begin with. Optional value, if it's not set meilies will start fron the end.
```suggestion
- from: Specifies the first event number to start reading from. Optional, if it's not set MeiliES, will start from the end.
```

2019-05-20 09:59 UTC, Kerollmops commented on meilies/src/reqresp/request.rs
> +                println!("{:?}", args);
Please remove that debug `println!`.

2019-05-20 09:59 UTC, Kerollmops commented on meilies/src/reqresp/request.rs
> +    SubscribeAll { from: ReadPosition, to: Option<u64> },
```suggestion
    SubscribeAll { from: ReadPosition, to: Option<EventNumber> },
```

2019-05-20 09:59 UTC, Kerollmops commented on meilies/src/stream/stream.rs
> +    pub to: Option<u64>,
```suggestion
    pub to: Option<EventNumber>,
```

2019-05-20 09:59 UTC, Kerollmops commented on meilies/src/stream/stream.rs
> +    pub fn all(from: ReadPosition, to: Option<u64>) -> Stream {
```suggestion
    pub fn all(from: ReadPosition, to: Option<EventNumber>) -> Stream {
```

2019-05-20 09:59 UTC, Kerollmops commented on meilies/src/stream/stream.rs
> +    pub fn new(name: StreamName, from: ReadPosition, to: Option<u64>) -> Stream {
```suggestion
    pub fn new(name: StreamName, from: ReadPosition, to: Option<EventNumber>) -> Stream {
```

2019-05-20 09:59 UTC, Kerollmops commented on meilies/src/stream/stream.rs
> +        match (self.to, self.from) {
Wouldn't it be more clear if you match in the other order (i.e. `(self.from, self.to)`) ?

2019-05-20 09:59 UTC, Kerollmops commented on meilies/src/stream/stream.rs
> +        let text = match (self.to, self.from) {
same as above

2019-05-20 09:59 UTC, Kerollmops commented on meilies/src/stream/stream.rs
> +            BoundsError => f.write_str("The end bound cannot be before or equal the start bound"),
```suggestion
            BoundsError => f.write_str("The end bound must be greater than the start bound"),
```

2019-05-20 09:59 UTC, Kerollmops commented on meilies/src/stream/stream.rs
>  }
I am asking myself, wouldn't it be better to unify these bounds in one type `ReadRange`?

```rust
enum ReadRange {
   ReadFromUntil(u64, u64),
   ReadFrom(u64),
   ReadToEnd,
}
```

2019-05-29 19:53 UTC, qdequele commented
@Kerollmops, all conversation are resolved.

2019-07-06 14:36 UTC, merged